# Sesión 3 · Análisis y Manipulación de Datos

<u>Estudios</u>: **Máster Universitario en Inteligencia Artificial**  
<u>Asignatura</u>: **Lenguajes de Programación para IA**

## Contacto

<u>Nombre</u>: 
<u>Correo electrónico</u>:

## Objetivos de aprendizaje

Al finalizar esta sesión serás capaz de:
- Comprender qué es **Pandas**, para qué se usa en IA y manejar sus estructuras principales: `Series` y `DataFrame`.
- Leer y escribir datos en distintos formatos: **CSV, Excel, JSON y Parquet**.
- Identificar y transformar **tipos de datos** (`dtypes`, `astype`, `category`) para optimizar memoria.
- Detectar y gestionar **valores faltantes** con `isna()`, `dropna()` y `fillna()` aplicando diversas estrategias de imputación.
- Seleccionar y filtrar información usando **condiciones lógicas**, `.loc[]` y `.iloc[]`.
- Obtener **estadísticas descriptivas** (`describe`, `value_counts`) y realizar **agregaciones** con `groupby` y múltiples funciones.
- Combinar DataFrames con **`merge()`** y **`concat()`** para unificar información de distintas fuentes.
- Aplicar **buenas prácticas de optimización**: reducción de memoria, lectura parcial de datos, vectorización y medición de tiempos con `%timeit`.
- Preparar un DataFrame para IA seleccionando **features relevantes**, aplicando **One-Hot Encoding**, **LabelEncoder** y **MinMaxScaler**, hasta obtener un dataset listo para modelado.

## 1. Preparación de entorno

> Ejecuta la siguiente celda para verificar la versión de Python y el entorno.

In [1]:
import sys, platform
print("Python:", sys.version)
print("Executable:", sys.executable)

Python: 3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\sandr\anaconda3\python.exe

> Importamos Pandas y le asignamos un alias

In [2]:
import os
import pandas as pd

> Documentación oficial Pandas: **https://pandas.pydata.org/**

## 2. Introducción a Pandas

### ¿Qué es Pandas?

**Pandas** es una librería de Python de **código abierto** diseñada para la manipulación y análisis de datos.  
Su nombre proviene de *Panel Data*, un término estadístico que hace referencia a datasets multidimensionales.  

Se ha convertido en un **estándar de facto** en la industria de la ciencia de datos e inteligencia artificial, ya que facilita el trabajo con **datos tabulares**.

---

### ¿Por qué Pandas es tan utilizado?

Antes de Pandas, trabajar con datos en Python era mucho más tedioso:
- Se usaban listas y diccionarios, que resultaban poco eficientes para operaciones complejas.
- Para cálculos numéricos existía **NumPy**, muy rápido, pero con estructuras poco expresivas para datos tabulares.

Pandas combina lo mejor de ambos mundos:
- **Velocidad** y eficiencia gracias a que está construido sobre **NumPy** y escrito en parte en **C**.
- **Expresividad** gracias a sus estructuras `Series` y `DataFrame`, que permiten representar datos de manera clara y manipulable.

En la práctica, Pandas ofrece:
- **Lectura/escritura** de datos en múltiples formatos (CSV, Excel, JSON, SQL, Parquet, HDF5...).
- **Selección y filtrado** de datos con sintaxis muy flexible.
- **Transformaciones**: aplicar funciones, renombrar columnas, crear nuevas variables.
- **Manejo de valores faltantes** de forma sencilla (`NaN`, `None`).
- **Agrupaciones y agregaciones** para análisis estadístico.
- **Operaciones vectorizadas** (mucho más rápidas que los bucles tradicionales).
- **Integración perfecta** con librerías de IA y Machine Learning (Scikit-learn, PyTorch, TensorFlow).

En resumen: **Pandas es el puente entre los datos en bruto y los modelos de IA.**

---

### ¿Qué tiene Pandas por debajo?

Para entender por qué Pandas es tan potente, conviene conocer qué hay bajo el capó:

- **NumPy**: Pandas se apoya en NumPy para el almacenamiento y cálculo eficiente de arrays multidimensionales.
- **Cython** y **C**: partes críticas de Pandas están optimizadas en bajo nivel para máxima velocidad.
- **Indexación**: cada `Series` y `DataFrame` tiene un índice que permite acceso rápido y flexible a los datos.
- **Operaciones vectorizadas**: en lugar de recorrer fila a fila, Pandas aplica operaciones a columnas enteras de forma optimizada.
- **Tipado eficiente**: Pandas maneja enteros, flotantes, cadenas, fechas, categorías... y permite ahorrar memoria con conversiones.

Esto significa que, aunque la sintaxis sea muy "amigable", Pandas está altamente optimizado para manejar **millones de filas** en memoria.

---

### ¿Por qué Pandas es clave en IA?

En un flujo de trabajo de Inteligencia Artificial, Pandas aparece en varias fases:

1. **Recolección de datos**  
   Lectura desde ficheros CSV, Excel, JSON o bases de datos.

2. **Limpieza de datos**  
   Manejo de valores nulos, duplicados, outliers.

3. **Transformación de datos**  
   Normalización, creación de nuevas variables, selección de columnas relevantes.

4. **Análisis exploratorio (EDA)**  
   Estadísticas rápidas, visualización previa con librerías como `plotly`, `matplotlib` o `seaborn`.

5. **Preparación del dataset**  
   División en train/test, exportación a NumPy arrays o tensores de PyTorch/TensorFlow.

En la práctica, **casi todos los proyectos de IA en Python comienzan con Pandas**.

---

### Estructuras principales: Series y DataFrame

#### 🔹 Series
Una **Serie** es un array unidimensional con etiquetas (índices).  
Podemos verla como una columna de Excel con nombre y posición.

El índice por defecto es 0, 1, 2..., pero puede personalizarse.

In [3]:
serie = pd.Series([10, 20, 30, 40], name="valores")
serie

0    10
1    20
2    30
3    40
Name: valores, dtype: int64

> Soporta operaciones vectorizadas:

In [4]:
print(serie * 2)

0    20
1    40
2    60
3    80
Name: valores, dtype: int64

#### 🔹 DataFrame
Un **DataFrame** es una tabla de dos dimensiones, formada por varias Series que comparten el mismo índice.  
Es la estructura más importante de Pandas.

In [5]:
df = pd.DataFrame({
    "nombre": ["Ana", "Luis", "Marta"],
    "edad": [23, 34, 29],
    "ciudad": ["Madrid", "Barcelona", "Valencia"]
})
df

  nombre  edad     ciudad
0    Ana    23     Madrid
1   Luis    34  Barcelona
2  Marta    29   Valencia

>Un DataFrame permite (entre otras cosas):
>- Seleccionar columnas.
>- Filtrar filas.
>- Combinar y unir tablas (merge, concat, join).
>- Agrupar y resumir (groupby).

In [6]:
# Seleccionar columnas 
df["nombre"]

0      Ana
1     Luis
2    Marta
Name: nombre, dtype: object

In [7]:
# Filtrar filas
df[df["edad"] > 25]

  nombre  edad     ciudad
1   Luis    34  Barcelona
2  Marta    29   Valencia

## 3. Lectura y Escritura de Datos con Pandas

Una de las mayores fortalezas de **Pandas** es su capacidad para **leer y escribir datos en múltiples formatos** de manera sencilla y unificada.  

En proyectos de Inteligencia Artificial, esta característica es crucial porque:
- Los datos provienen de fuentes muy diversas (CSV, Excel, JSON, bases de datos, Big Data…).
- Durante el proceso de experimentación y entrenamiento, necesitamos guardar resultados intermedios.
- Pandas permite moverse entre diferentes ecosistemas sin tener que aprender librerías distintas para cada formato.

---

### <u>Lectura de datos</u>

La función principal es `pd.read_<formato>`.  
Internamente, Pandas cuenta con parsers optimizados para cada tipo de fichero.

##### **1. CSV (Comma-Separated Values)**

> Es el formato más común en datasets abiertos (Kaggle, UCI, etc.).
>
> <u>Pros</u>: universal, ligero, fácil de abrir incluso en un editor de texto.  
> <u>Contras</u>: no almacena tipos de datos de forma explícita (todo llega como texto y hay que convertirlo).

<u>TIP</u> Úsalo cuando compartas datos pequeños/medianos o quieras máxima compatibilidad.

In [15]:
df_csv = pd.read_csv(os.path.join(os.getcwd(), "titanic_demo", "titanic_demo.csv"))
df_csv.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,3,0,"Rintamaki, Mr. Matti",male,35.0,0,0,STON/O 2. 3101273,7.1250,NaN,S
1,3,1,"Nakid, Mr. Sahid",male,20.0,1,1,2653,15.7417,NaN,C
2,3,0,"Lyntakoff, Mr. Stanko",male,NaN,0,0,349235,7.8958,NaN,S
3,3,0,"Ford, Mr. Arthur",male,NaN,0,0,A/5 1478,8.0500,NaN,S
4,3,0,"Shaughnessy, Mr. Patrick",male,NaN,0,0,370374,7.7500,NaN,Q

In [16]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    200 non-null    int64
 1   survived  200 non-null    int64
 2   name      200 non-null    object
 3   sex       200 non-null    object
 4   age       154 non-null    float64
 5   sibsp     200 non-null    int64
 6   parch     200 non-null    int64
 7   ticket    200 non-null    object
 8   fare      200 non-null    float64
 9   cabin     48 non-null     object
 10  embarked  199 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 17.3+ KB

##### **2. EXCEL**

> Pandas puede leer y escribir ficheros Excel (.xls, .xlsx).
>
> <u>Pros</u>: muy usado en empresas, soporta múltiples hojas.  
> <u>Contras</u>: más pesado, más lento, depende de librerías externas (openpyxl, xlrd).

<u>TIP</u> Úsalo para integrarte con entornos corporativos o cuando recibas datos de analistas que trabajan en Excel.

In [17]:
df_excel = pd.read_excel(os.path.join(os.getcwd(), "titanic_demo", "titanic_demo.xlsx"), sheet_name="Sheet1")
df_excel.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,3,0,"Rintamaki, Mr. Matti",male,35.0,0,0,STON/O 2. 3101273,7.1250,NaN,S
1,3,1,"Nakid, Mr. Sahid",male,20.0,1,1,2653,15.7417,NaN,C
2,3,0,"Lyntakoff, Mr. Stanko",male,NaN,0,0,349235,7.8958,NaN,S
3,3,0,"Ford, Mr. Arthur",male,NaN,0,0,A/5 1478,8.0500,NaN,S
4,3,0,"Shaughnessy, Mr. Patrick",male,NaN,0,0,370374,7.7500,NaN,Q

##### **3. JSON**

> Formato clave en aplicaciones web y APIs.
>
> <u>Pros</u>: flexible, ideal para datos jerárquicos o semi-estructurados.  
> <u>Contras</u>: puede ser ambiguo si no está bien definido el esquema.

<u>TIP</u> Úsalo cuando consumas datos de APIs REST o tengas estructuras anidadas.

In [18]:
df_json = pd.read_json(os.path.join(os.getcwd(), "titanic_demo", "titanic_demo.json"))
df_json.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,3,0,"Rintamaki, Mr. Matti",male,35.0,0,0,STON/O 2. 3101273,7.1250,None,S
1,3,1,"Nakid, Mr. Sahid",male,20.0,1,1,2653,15.7417,None,C
2,3,0,"Lyntakoff, Mr. Stanko",male,NaN,0,0,349235,7.8958,None,S
3,3,0,"Ford, Mr. Arthur",male,NaN,0,0,A/5 1478,8.0500,None,S
4,3,0,"Shaughnessy, Mr. Patrick",male,NaN,0,0,370374,7.7500,None,Q

##### **4. PARQUET**

> Formato columnar optimizado para Big Data (basado en Apache Arrow).
>
> <u>Pros</u>: muy eficiente en espacio y velocidad, soporta compresión y tipado explícito.  
> <u>Contras</u>: menos humano-legible que CSV o Excel.

<u>TIP</u> Úsalo cuando trabajes con datasets grandes y quieras máxima eficiencia.  
Es el formato estándar en ecosistemas como Spark, Hadoop, AWS, Azure y GCP.

```python
df_parquet = pd.read_parquet("datos.parquet")
print(df_parquet.head())
```

##### **5. OTROS FORMATOS SOPORTADOS POR PANDAS**

>- Pickle (.pkl): serialización de objetos como binarios.
>- HDF5 (.h5): rápido, binario, para almacenamiento local.  
>- SQL: conexión directa a bases de datos con pd.read_sql.  
>- Clipboard: incluso se puede leer desde el portapapeles (pd.read_clipboard()).

---

### <u>Escritura de datos</u>

De forma simétrica, Pandas ofrece funciones df.to_`<formato>` para guardar resultados.

In [20]:
# Guardar en CSV
df_csv.to_csv("resultado.csv", index=False)

# Guardar en Excel
df_excel.to_excel("resultado.xlsx", index=False)

# Guardar en JSON
df_json.to_json("resultado.json", orient="records")

Notas importantes:
- El parámetro index=False evita que el índice del DataFrame se guarde como columna extra.  
  La documentación de la función `to_csv()` es: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html
- orient en JSON controla la forma de exportar los datos (records, split, table...).  
  La documentación de la función `to_json()` es: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html
- En Excel puedes guardar múltiples hojas usando ExcelWriter.  
  La documentación de la función `to_excel()` es: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html
- La documentación de la función `to_parquet()` es: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_parquet.html

### <u>Comparación de formatos:</u>  
| Formato     | Ventajas                                          | Desventajas              | Uso recomendado                             |
| ----------- | ------------------------------------------------- | ------------------------ | ------------------------------------------- |
| **CSV**     | Ligero, universal, editable con cualquier editor  | No guarda tipos de datos | Datasets pequeños/medianos, compatibilidad  |
| **Excel**   | Familiar, múltiple hojas, integración empresarial | Pesado, más lento        | Entornos corporativos, informes             |
| **JSON**    | Flexible, ideal para datos jerárquicos y APIs     | Puede ser ambiguo        | APIs REST, estructuras semi-estructuradas   |
| **Parquet** | Eficiente, compresión, pensado para Big Data      | No legible por humanos   | Grandes volúmenes, ecosistemas distribuidos |
| **HDF5**    | Muy rápido, binario                               | Menos portable           | Almacenamiento local rápido                 |
| **SQL**     | Integración directa con bases de datos            | Necesita conexión activa | Datos en producción / empresariales         |

### <u>Ejemplo práctico: flujo de datos en un proyecto:</u>  

1. Descargas un dataset en CSV desde Kaggle.
2. Lo cargas con pd.read_csv().
3. Tras limpieza y transformación, lo guardas en Parquet para acelerar futuros experimentos.
4. Exportas resultados intermedios en Excel para mostrarlos a un analista de negocio.
5. Subes los resultados a una base de datos SQL de producción.

Este ejemplo muestra cómo Pandas conecta distintos mundos en un solo flujo de trabajo.

---

## 4. Tipos de datos y conversión

### <u>Los `dtypes` en Pandas</u>

Cada columna de un **DataFrame** tiene un tipo de datos asociado (`dtype`).  
Estos tipos definen cómo se almacenan los valores en memoria y qué operaciones son posibles.

Ejemplo con el dataset Titanic reducido:

In [23]:
df_csv = pd.read_csv(os.path.join(os.getcwd(), "titanic_demo", "titanic_demo.csv"))
df_csv.dtypes

pclass        int64
survived      int64
name         object
sex          object
age         float64
sibsp         int64
parch         int64
ticket       object
fare        float64
cabin        object
embarked     object
dtype: object

Observaciones:
- `int64`: números enteros.
- `float64`: números decimales.
- `object`: tipo genérico en Pandas (normalmente cadenas de texto).
- `category`: tipo especial para valores repetitivos (lo veremos más abajo).
- `datetime64`: fechas y tiempos.

### <u>Conversión de tipos (casting)</u>

Podemos cambiar el tipo de una columna con `.astype()`:

In [28]:
# Convertir survived a booleano
df_csv["survived_bool"] = df_csv["survived"].astype(bool)

# Convertir embarque a string explícito
df_csv["embarked_str"] = df_csv["embarked"].astype(str)

<u>Importante:</u>
> `int64` no acepta valores nulos.  
> `Int64` (con mayúscula) es un tipo Pandas que sí admite NaN.

### <u>Conversión automática al leer datos</u>

Cuando usamos `read_csv` o similares, Pandas intenta adivinar el tipo de cada columna.  
Esto funciona en muchos casos, pero a veces conviene especificar `dtype` en la lectura:

In [29]:
df = pd.read_csv(
    os.path.join(os.getcwd(), "titanic_demo", "titanic_demo.csv"),
    dtype={"survived": "int8", "pclass": "category"}
)
df.dtypes

pclass      category
survived        int8
name          object
sex           object
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked      object
dtype: object

>- `int8`: ocupa menos memoria que `int64` (útil si los valores son pequeños).  
>- `category`: convierte directamente a tipo categórico.

### <u>El tipo `category`</u>

Las columnas con pocos valores repetidos se pueden convertir a categorías.  
Esto reduce el uso de memoria y acelera operaciones de agrupación.

Ejemplo:

In [30]:
df["sex"] = df["sex"].astype("category")
df["embarked"] = df["embarked"].astype("category")

print(df.dtypes)
print(df["sex"].cat.categories)

pclass      category
survived        int8
name          object
sex         category
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked    category
dtype: object
Index(['female', 'male'], dtype='object')

>- Internamente, Pandas guarda las categorías como números enteros, asociados a un diccionario de etiquetas.
>- Ventaja: ahorro de memoria y rapidez en filtros y `groupby`.

### <u>Fechas y tiempos (datetime64)</u>

Otra conversión habitual es pasar texto a fechas:

In [31]:
fechas = pd.Series(["2024-01-01", "2024-02-15", "2024-03-10"])
fechas = pd.to_datetime(fechas)
print(fechas)

0   2024-01-01
1   2024-02-15
2   2024-03-10
dtype: datetime64[ns]

Esto permite usar atributos y operaciones:

In [32]:
print(fechas.dt.month)   # Mes
print(fechas.dt.weekday) # Día de la semana

0    1
1    2
2    3
dtype: int64
0    0
1    3
2    6
dtype: int64

### <u>Optimización de memoria</u>

En datasets grandes, optimizar `dtypes` puede reducir el uso de memoria drásticamente:

In [33]:
print("Antes:")
print(df.dtypes)
print(df.memory_usage(deep=True))
print("\n"+"-"*30)

# Ejemplo de optimización
df_opt = df.copy()
df_opt["pclass"] = df_opt["pclass"].astype("int8")
df_opt["survived"] = df_opt["survived"].astype("int8")
df_opt["sex"] = df_opt["sex"].astype("category")
df_opt["embarked"] = df_opt["embarked"].astype("category")

print("\nDespués:")
print(df_opt.dtypes)
print(df_opt.memory_usage(deep=True))

Antes:
pclass      category
survived        int8
name          object
sex         category
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked    category
dtype: object
Index         132
pclass        482
survived      200
name        16887
sex           432
age          1600
sibsp        1600
parch        1600
ticket      12789
fare         1600
cabin        7784
embarked      482
dtype: int64

------------------------------

Después:
pclass          int8
survived        int8
name          object
sex         category
age          float64
sibsp          int64
parch          int64
ticket        object
fare         float64
cabin         object
embarked    category
dtype: object
Index         132
pclass        200
survived      200
name        16887
sex           432
age          1600
sibsp        1600
parch        1600
ticket      12789
fare         1600
cabin        7784
embarked      482
dtype: int64

>**Claves para optimizar:**
>- Usar int8, int16 o float32 en lugar de int64/float64 si los valores lo permiten.
>- Convertir columnas con pocos valores distintos a category.
>- Usar datetime64 para fechas.

#### ¿Cuándo usar `int8`, `int16` o `float32` en lugar de `int64`/`float64`?

Por defecto, Pandas asigna a los números enteros el tipo **`int64`** y a los decimales **`float64`**.  
Estos tipos ocupan **8 bytes por valor** y permiten representar números muy grandes, mucho más de lo que normalmente necesitamos en un dataset típico.

🔹 Tipos enteros (`int`)

- `int8` → ocupa 1 byte → valores entre **-128 y 127**  
- `int16` → ocupa 2 bytes → valores entre **-32,768 y 32,767**  
- `int32` → ocupa 4 bytes → valores entre **-2,147,483,648 y 2,147,483,647**  
- `int64` → ocupa 8 bytes → valores muy grandes (≈9e18)

👉 Recomendación:
- Si una columna contiene identificadores pequeños (ejemplo: `pclass` en Titanic, que solo puede ser 1, 2 o 3) → usar `int8`.
- Si una columna contiene recuentos modestos (ejemplo: número de hijos, `parch`, o de hermanos, `sibsp`, que nunca pasan de 10) → usar `int8` o `int16`.
- Solo usar `int64` si realmente hay números muy grandes (ejemplo: IDs enormes o valores acumulativos).

---

🔹 Tipos decimales (`float`)

- `float32` → ocupa 4 bytes → precisión de unos **7 decimales**  
- `float64` → ocupa 8 bytes → precisión de unos **15 decimales**

👉 Recomendación:
- Para columnas de dinero, precios o medidas donde no necesitamos tanta precisión → usar `float32`.
- Para cálculos financieros o científicos que requieran alta precisión → mantener `float64`.
- En Machine Learning, muchas librerías (TensorFlow, PyTorch) trabajan con `float32` por defecto, ya que ahorra memoria y es más rápido en GPU.

---

## 5. Limpieza y manejo de missing values

En datasets reales, es muy común encontrarse con valores **faltantes** (missing values).  
En Pandas, los valores faltantes suelen representarse como **`NaN`** (*Not a Number*) o `None`.

Detectarlos y tratarlos es una de las tareas más importantes antes de entrenar un modelo de IA.

---

### <u>Detección de Missing Values</u>

- **`isna()`** → devuelve un booleano indicando si cada valor es nulo.  
- **`notna()`** → lo contrario.

In [34]:
df = pd.read_csv(os.path.join(os.getcwd(), "titanic_demo", "titanic_demo.csv"))

# Detectar valores nulos en cada celda
print(df.isna().head(10))

print("-"*100)

# Contar valores nulos por columna
print(df.isna().sum())

   pclass  survived   name    sex    age  sibsp  parch  ticket   fare  cabin  \
0   False     False  False  False  False  False  False   False  False   True
1   False     False  False  False  False  False  False   False  False   True
2   False     False  False  False   True  False  False   False  False   True
3   False     False  False  False   True  False  False   False  False   True
4   False     False  False  False   True  False  False   False  False   True
5   False     False  False  False  False  False  False   False  False   True
6   False     False  False  False  False  False  False   False  False   True
7   False     False  False  False  False  False  False   False  False   True
8   False     False  False  False  False  False  False   False  False   True
9   False     False  False  False  False  False  False   False  False  False

   embarked
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
----------------------------------------------------------------------------------------------------
pclass        0
survived      0
name          0
sex           0
age          46
sibsp         0
parch         0
ticket        0
fare          0
cabin       152
embarked      1
dtype: int64

### <u>Eliminación de Missing Values</u>

- **`dropna()`** → Elimina filas o columnas con valores nulos.

In [35]:
# Eliminar filas con al menos un valor nulo
df_sin_nulos = df.dropna()

# Eliminar columnas con valores nulos
df_sin_nulos_cols = df.dropna(axis=1)

In [36]:
df.head(20)
# df_sin_nulos.head(20)
# df_sin_nulos_cols.head(20)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,3,0,"Rintamaki, Mr. Matti",male,35.0,0,0,STON/O 2. 3101273,7.1250,NaN,S
1,3,1,"Nakid, Mr. Sahid",male,20.0,1,1,2653,15.7417,NaN,C
2,3,0,"Lyntakoff, Mr. Stanko",male,NaN,0,0,349235,7.8958,NaN,S
3,3,0,"Ford, Mr. Arthur",male,NaN,0,0,A/5 1478,8.0500,NaN,S
4,3,0,"Shaughnessy, Mr. Patrick",male,NaN,0,0,370374,7.7500,NaN,Q
5,1,1,"Romaine, Mr. Charles Hallace ('Mr C Rolmane')",male,45.0,0,0,111428,26.5500,NaN,S
6,3,0,"Peltomaki, Mr. Nikolai Johannes",male,25.0,0,0,STON/O 2. 3101291,7.9250,NaN,S
7,2,1,"Wilhelms, Mr. Charles",male,31.0,0,0,244270,13.0000,NaN,S
8,3,0,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
9,1,1,"Chambers, Mrs. Norman Campbell (Bertha Griggs)",female,33.0,1,0,113806,53.1000,E8,S
10,3,0,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S
11,3,0,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
12,3,1,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C
13,3,0,"Ivanoff, Mr. Kanio",male,NaN,0,0,349201,7.8958,NaN,S
14,3,0,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
15,3,1,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
16,3,0,"Saad, Mr. Amin",male,NaN,0,0,2671,7.2292,NaN,C
17,3,1,"Nilsson, Miss. Helmina Josefina",female,26.0,0,0,347470,7.8542,NaN,S
18,1,1,"White, Mrs. John Stuart (Ella Holmes)",female,55.0,0,0,PC 17760,135.6333,C32,C
19,3,0,"Dean, Mr. Bertram Frank",male,26.0,1,2,C.A. 2315,20.5750,NaN,S

> **IMPORTANTE**:
>- Usar esta estrategia solo cuando los nulos son pocos o irrelevantes.
>- Si se eliminan demasiados, se puede perder información valiosa.

### <u>Relleno de Missing Values</u>

- **`fillna()`** → Permite reemplazar los nulos con un valor concreto.

In [37]:
# Rellenar edad con la media
df["age_fill_mean"] = df["age"].fillna(df["age"].mean())

# Rellenar edad con la mediana
df["age_fill_median"] = df["age"].fillna(df["age"].median())

# Rellenar con un valor fijo
df["age_fill_0"] = df["age"].fillna(0)

df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,age_fill_mean,age_fill_median,age_fill_0
0,3,0,"Rintamaki, Mr. Matti",male,35.0,0,0,STON/O 2. 3101273,7.1250,NaN,S,35.000000,35.0,35.0
1,3,1,"Nakid, Mr. Sahid",male,20.0,1,1,2653,15.7417,NaN,C,20.000000,20.0,20.0
2,3,0,"Lyntakoff, Mr. Stanko",male,NaN,0,0,349235,7.8958,NaN,S,31.780303,29.0,0.0
3,3,0,"Ford, Mr. Arthur",male,NaN,0,0,A/5 1478,8.0500,NaN,S,31.780303,29.0,0.0
4,3,0,"Shaughnessy, Mr. Patrick",male,NaN,0,0,370374,7.7500,NaN,Q,31.780303,29.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,3,0,"Sirayanian, Mr. Orsen",male,22.0,0,0,2669,7.2292,NaN,C,22.000000,22.0,22.0
196,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,35.000000,35.0,35.0
197,3,0,"Sage, Miss. Constance Gladys",female,NaN,8,2,CA. 2343,69.5500,NaN,S,31.780303,29.0,0.0
198,2,1,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)",female,36.0,0,3,230136,39.0000,F4,S,36.000000,36.0,36.0
199,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,B28,NaN,38.000000,38.0,38.0

### <u>Estrategia de imputación de Missing Values</u>

Dependiendo del tipo de dato y del problema, se pueden aplicar diferentes estrategias:

- **Eliminar filas con valores nulos** → recomendable solo si representan menos del **5%** del dataset.  

- **Reemplazar por estadísticos**:
  - **Media** → para datos numéricos distribuidos de forma normal.  
  - **Mediana** → para datos numéricos con **outliers**.  
  - **Moda** → para datos categóricos (el valor más frecuente).  

- **Forward Fill (`ffill`) / Backward Fill (`bfill`)** → arrastrar el valor anterior o posterior en la columna.  

- **Imputación avanzada** → usar algoritmos de Machine Learning para predecir los valores faltantes (ejemplo: `KNNImputer` de *Scikit-learn*).

In [38]:
# Forward fill
df["age_ffill"] = df["age"].ffill()

# Backward fill
df["age_bfill"] = df["age"].bfill()

df

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,age_fill_mean,age_fill_median,age_fill_0,age_ffill,age_bfill
0,3,0,"Rintamaki, Mr. Matti",male,35.0,0,0,STON/O 2. 3101273,7.1250,NaN,S,35.000000,35.0,35.0,35.0,35.0
1,3,1,"Nakid, Mr. Sahid",male,20.0,1,1,2653,15.7417,NaN,C,20.000000,20.0,20.0,20.0,20.0
2,3,0,"Lyntakoff, Mr. Stanko",male,NaN,0,0,349235,7.8958,NaN,S,31.780303,29.0,0.0,20.0,45.0
3,3,0,"Ford, Mr. Arthur",male,NaN,0,0,A/5 1478,8.0500,NaN,S,31.780303,29.0,0.0,20.0,45.0
4,3,0,"Shaughnessy, Mr. Patrick",male,NaN,0,0,370374,7.7500,NaN,Q,31.780303,29.0,0.0,20.0,45.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,3,0,"Sirayanian, Mr. Orsen",male,22.0,0,0,2669,7.2292,NaN,C,22.000000,22.0,22.0,22.0,22.0
196,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,35.000000,35.0,35.0,35.0,35.0
197,3,0,"Sage, Miss. Constance Gladys",female,NaN,8,2,CA. 2343,69.5500,NaN,S,31.780303,29.0,0.0,35.0,36.0
198,2,1,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)",female,36.0,0,3,230136,39.0000,F4,S,36.000000,36.0,36.0,36.0,36.0
199,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,B28,NaN,38.000000,38.0,38.0,38.0,38.0

---

## 6. Filtrado e indexación

Una de las características más potentes de Pandas es la capacidad de **seleccionar** y **filtrar** datos de forma flexible.

Trabajar con datos significa, casi siempre, **seleccionar subconjuntos** de un DataFrame:  
- Filtrar filas que cumplen ciertas condiciones.  
- Seleccionar columnas específicas.  
- Acceder a posiciones concretas.  
- Modificar valores en función de un criterio.  

En Pandas existen varias formas de hacerlo: **operadores lógicos, `.loc[]`, `.iloc[]`, y acceso directo a columnas**.

### <u>Filtrado con condiciones lógicas</u>

El filtrado más común consiste en aplicar condiciones sobre columnas:

In [39]:
# Pasajeros mayores de 30 años
df[df["age"] > 30]

# Mujeres en primera clase
# df[(df["sex"] == "female") & (df["pclass"] == 1)]

# Pasajeros con tarifa > 50 o menores de 18
# df[(df["fare"] > 50) | (df["age"] < 18)]

# Pasajeros que NO embarcaron en Southampton
# df[~(df["embarked"] == "S")]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,age_fill_mean,age_fill_median,age_fill_0,age_ffill,age_bfill
0,3,0,"Rintamaki, Mr. Matti",male,35.0,0,0,STON/O 2. 3101273,7.1250,NaN,S,35.0,35.0,35.0,35.0,35.0
5,1,1,"Romaine, Mr. Charles Hallace ('Mr C Rolmane')",male,45.0,0,0,111428,26.5500,NaN,S,45.0,45.0,45.0,45.0,45.0
7,2,1,"Wilhelms, Mr. Charles",male,31.0,0,0,244270,13.0000,NaN,S,31.0,31.0,31.0,31.0,31.0
8,3,0,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,34.5,34.5,34.5,34.5,34.5
9,1,1,"Chambers, Mrs. Norman Campbell (Bertha Griggs)",female,33.0,1,0,113806,53.1000,E8,S,33.0,33.0,33.0,33.0,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,3,0,"Turcin, Mr. Stjepan",male,36.0,0,0,349247,7.8958,NaN,S,36.0,36.0,36.0,36.0,36.0
189,3,0,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41.0,0,2,370129,20.2125,NaN,S,41.0,41.0,41.0,41.0,41.0
196,3,0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,35.0,35.0,35.0,35.0,35.0
198,2,1,"Becker, Mrs. Allen Oliver (Nellie E Baumgardner)",female,36.0,0,3,230136,39.0000,F4,S,36.0,36.0,36.0,36.0,36.0
199,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0000,B28,NaN,38.0,38.0,38.0,38.0,38.0

> **Operadores disponibles:**
>- `&` → AND lógico (ambas condiciones se cumplen).
>- `|` → OR lógico (se cumple al menos una condición).
>- `~` → NOT lógico (invierte la condición).

⚠️ Importante: hay que usar paréntesis en cada condición, si no Pandas lanza error de precedencia.

### <u>Selección de columnas</u>

Existen varias formas de seleccionar columnas:

In [40]:
# Una columna (devuelve Series)
df["age"]

# Varias columnas (devuelve DataFrame)
# df[["age", "sex", "fare"]]

0      35.0
1      20.0
2       NaN
3       NaN
4       NaN
       ...
195    22.0
196    35.0
197     NaN
198    36.0
199    38.0
Name: age, Length: 200, dtype: float64

> La selección de columnas puede combinarse con condiciones de filas:

In [41]:
# Mujeres menores de 20, solo columnas edad y tarifa
df[(df["sex"] == "female") & (df["age"] < 20)][["age", "fare"]]

      age     fare
12   14.0  11.2417
25    9.0  15.2458
47   18.0   8.0500
97   18.0  60.0000
109  18.0  53.1000
113  17.0  12.0000
130  15.0   8.0292
148  18.0   6.7500
156  12.0  15.7500
164   1.0  41.5792
174   6.0  33.0000
188  19.0  15.7417

### <u>Selección por etiquetas `.loc[]`</u>

`.loc[]` permite seleccionar **filas y columnas por nombre/etiqueta**

Sintaxis:

```python
df.loc[filas, columnas]

In [42]:
# Fila con índice 0
df.loc[0]

# Filas del 0 al 4 y columnas "sex" y "age"
# df.loc[0:4, ["sex", "age"]]

# Pasajeros mujeres, seleccionando edad y tarifa
# df.loc[df["sex"] == "female", ["age", "fare"]]

pclass                                3
survived                              0
name               Rintamaki, Mr. Matti
sex                                male
age                                35.0
sibsp                                 0
parch                                 0
ticket                STON/O 2. 3101273
fare                              7.125
cabin                               NaN
embarked                              S
age_fill_mean                      35.0
age_fill_median                    35.0
age_fill_0                         35.0
age_ffill                          35.0
age_bfill                          35.0
Name: 0, dtype: object

> Características:
>- El rango de índices es inclusivo (0:4 incluye la fila 4).
>- Se puede usar con condiciones, listas de índices o etiquetas.

### <u>Selección por posicion `.iloc[]`</u>

`.iloc[]` selecciona por **posición numérica** (similar a arrays NumPy).

Sintaxis:

```python
df.iloc[filas, columnas]

In [43]:
# Primera fila
df.iloc[0]

# Primeras 3 filas y primeras 2 columnas
# df.iloc[0:3, 0:2]

# Elemento en fila 5, columna 3
# df.iloc[5, 3]

pclass                                3
survived                              0
name               Rintamaki, Mr. Matti
sex                                male
age                                35.0
sibsp                                 0
parch                                 0
ticket                STON/O 2. 3101273
fare                              7.125
cabin                               NaN
embarked                              S
age_fill_mean                      35.0
age_fill_median                    35.0
age_fill_0                         35.0
age_ffill                          35.0
age_bfill                          35.0
Name: 0, dtype: object

> Características:
>- El rango es exclusivo en el final, como en Python (0:3 incluye filas 0,1,2).
>- Muy útil cuando no conoces los nombres de las columnas, solo su posición.

### <u>Diferencias clave entre `.loc[]` y `.iloc[]`</u>

| Método    | Selección                    | Ejemplo              | Inclusividad         |
| --------- | ---------------------------- | -------------------- | -------------------- |
| `.loc[]`  | Por **etiquetas** (nombres)  | `df.loc[0:2, "age"]` | Incluye índice final |
| `.iloc[]` | Por **posiciones** (números) | `df.iloc[0:2, 3]`    | Excluye índice final |

> Regla práctica:
>- Usa `.loc[]` si trabajas con nombres de filas o columnas.
>- Usa `.iloc[]` si trabajas con posiciones numéricas.

### <u>Modificación de valores mediante indexación</u>

No solo permite leer, también modificar:

In [44]:
# Cambiar la edad de la fila 0 a 30
df.loc[0, "age"] = 30

# Aumentar tarifa un 10% para todos los pasajeros de primera clase
# df.loc[df["pclass"] == 1, "fare"] *= 1.1

### <u>Indexación avanzada `.set_index()` y `.reset_index()`</u>

El índice es la etiqueta de las filas.  
Podemos usar cualquier columna como índice para facilitar búsquedas.

In [45]:
# Usar "sex" como índice
df_idx = df.set_index("sex")
display(df_idx.head())

# Volver al índice numérico estándar
df_reset = df_idx.reset_index()
df_reset.head()

,pclass,survived,name,age,sibsp,parch,ticket,fare,cabin,embarked,age_fill_mean,age_fill_median,age_fill_0,age_ffill,age_bfill
sex,,,,,,,,,,,,,,,
male,3,0,"Rintamaki, Mr. Matti",30.0,0,0,STON/O 2. 3101273,7.1250,NaN,S,35.000000,35.0,35.0,35.0,35.0
male,3,1,"Nakid, Mr. Sahid",20.0,1,1,2653,15.7417,NaN,C,20.000000,20.0,20.0,20.0,20.0
male,3,0,"Lyntakoff, Mr. Stanko",NaN,0,0,349235,7.8958,NaN,S,31.780303,29.0,0.0,20.0,45.0
male,3,0,"Ford, Mr. Arthur",NaN,0,0,A/5 1478,8.0500,NaN,S,31.780303,29.0,0.0,20.0,45.0
male,3,0,"Shaughnessy, Mr. Patrick",NaN,0,0,370374,7.7500,NaN,Q,31.780303,29.0,0.0,20.0,45.0

,sex,pclass,survived,name,age,sibsp,parch,ticket,fare,cabin,embarked,age_fill_mean,age_fill_median,age_fill_0,age_ffill,age_bfill
0,male,3,0,"Rintamaki, Mr. Matti",30.0,0,0,STON/O 2. 3101273,7.1250,NaN,S,35.000000,35.0,35.0,35.0,35.0
1,male,3,1,"Nakid, Mr. Sahid",20.0,1,1,2653,15.7417,NaN,C,20.000000,20.0,20.0,20.0,20.0
2,male,3,0,"Lyntakoff, Mr. Stanko",NaN,0,0,349235,7.8958,NaN,S,31.780303,29.0,0.0,20.0,45.0
3,male,3,0,"Ford, Mr. Arthur",NaN,0,0,A/5 1478,8.0500,NaN,S,31.780303,29.0,0.0,20.0,45.0
4,male,3,0,"Shaughnessy, Mr. Patrick",NaN,0,0,370374,7.7500,NaN,Q,31.780303,29.0,0.0,20.0,45.0

> Esto es útil en merges, joins y operaciones de agrupación.

### 📝 **Ejercicios**

---

**1. Clasificación de pasajeros por edad:**  

Crea una nueva columna `age_label` con los siguientes valores:
- `"menor"` si la edad es < 18  
- `"adulto"` si la edad está entre 18 y 60  
- `"mayor"` si la edad es >= 60  

⚠️ Ten en cuenta que `age` tiene valores nulos: decide cómo gestionarlos antes de crear la nueva columna.

---

**2. Detección de tarifas extremas:**  

Filtra el DataFrame para obtener:
- Pasajeros con tarifa (`fare`) mayor de 50.  
- Pasajeros con tarifa menor de 10.  

Muestra únicamente las columnas `sex`, `age` y `fare`.  

---

**3. Modificación condicional de valores:**  

Crea una nueva columna `fare_adjusted` que incremente la tarifa (`fare`) un 20% **solo para los pasajeros de primera clase**.  
El resto deben mantener su tarifa original.

---

**4. Uso combinado de `.loc[]`:**  

- Selecciona los pasajeros que tienen edad conocida y son menores de 20 años.  
- Devuelve únicamente `sex`, `age`, `pclass` y `embarked`.  

---

**5. Indexación mixta con `.iloc[]`:**  

- Selecciona las filas 3 a 7 (inclusive).  
- De esas filas, muestra solo las columnas 2 a 5 (por posición).  

---

## 7. Agregaciones y estadísticas

Una vez que tenemos los datos limpios y organizados, el siguiente paso es **resumirlos**:  
- Calcular estadísticas descriptivas.  
- Contar frecuencias de valores.  
- Agrupar datos en categorías y obtener métricas por grupo.  

Estas operaciones son fundamentales en el **Análisis Exploratorio de Datos (EDA)** y en la preparación de datasets para IA.

### <u>Estadísticas descriptivas: `.describe()`</u>

El método `.describe()` devuelve un resumen estadístico de todas las columnas numéricas (o de las categóricas si se especifica).

In [46]:
df = pd.read_csv(os.path.join(os.getcwd(), "titanic_demo", "titanic_demo.csv"))
df.describe()

           pclass    survived         age       sibsp       parch        fare
count  200.000000  200.000000  154.000000  200.000000  200.000000  200.000000
mean     2.295000    0.465000   31.780303    0.405000    0.320000   34.234291
std      0.855356    0.500025   14.819523    1.047119    0.685529   55.811594
min      1.000000    0.000000    0.666700    0.000000    0.000000    0.000000
25%      1.000000    0.000000   22.000000    0.000000    0.000000    7.895800
50%      3.000000    0.000000   29.000000    0.000000    0.000000   13.000000
75%      3.000000    1.000000   39.000000    0.000000    0.000000   32.012475
max      3.000000    1.000000   70.000000    8.000000    4.000000  512.329200

👉 De un vistazo puedes ver **media, desviación estándar, cuartiles, mínimos y máximos**.

Puedes incluir estadísticas de columnas categóricas con:

In [47]:
df.describe(include="object")

                        name   sex ticket        cabin embarked
count                    200   200    200           48      199
unique                   200     2    188           43        3
top     Rintamaki, Mr. Matti  male   1601  C23 C25 C27        S
freq                       1   121      3            2      135

### <u>Conteo de valores: `.value_counts()`</u>

Sirve para conocer la frecuencia de valores únicos en una columna.

In [48]:
df["sex"].value_counts()

male      121
female     79
Name: sex, dtype: int64

In [49]:
df["embarked"].value_counts()

S    135
C     47
Q     17
Name: embarked, dtype: int64

**Opciones útiles:**
- `normalize=True` → muestra porcentajes en lugar de conteos.  
- `dropna=False` → incluye valores nulos en el conteo.

In [50]:
df["embarked"].value_counts(normalize=True, dropna=False)

S      0.675
C      0.235
Q      0.085
NaN    0.005
Name: embarked, dtype: float64

### <u>Agrupación de datos: `.groupby()`</u>

El método `.groupby()` permite agrupar los datos por una o varias columnas y aplicar funciones de agregación.

Ejemplo: **edad media por sexo**.

In [51]:
df.groupby("sex")["age"].mean()

sex
female    32.007576
male      31.609849
Name: age, dtype: float64

Ejemplo: **tarifa media por puerto de embarque**.

In [52]:
df.groupby("embarked")["fare"].mean()

embarked
C    61.814540
Q    14.377947
S    26.793701
Name: fare, dtype: float64

Ejemplo: **tarifa media por puerto de embarque y sexo**.

In [53]:
df.groupby(["sex", "embarked"])["fare"].mean()

sex     embarked
female  C           78.212877
        Q           16.487158
        S           41.590816
male    C           47.384004
        Q            9.315840
        S           19.639053
Name: fare, dtype: float64

### <u>Múltiples funciones de agregación</u>

Podemos aplicar varias funciones a la vez usando `.agg()`.

In [54]:
# Tarifa media y máxima por clase
df.groupby("pclass")["fare"].agg(["mean", "max"])

             mean       max
pclass
1       88.871394  512.3292
2       21.524214   73.5000
3       12.875223   69.5500

In [55]:
# Agregar diferentes columnas con diferentes funciones
df.groupby("sex").agg({
    "age": "median",
    "fare": ["mean", "min", "max"],
    "survived": "sum"
})

          age       fare                 survived
       median       mean   min       max      sum
sex
female   30.0  48.462343  6.75  263.0000       63
male     28.0  24.944902  0.00  512.3292       30

## 8. Combinación y Merge de DataFrames

En proyectos de IA y ciencia de datos es muy común tener la información repartida en varios ficheros o tablas.  
Pandas ofrece herramientas para **combinar y unir DataFrames** de forma muy parecida a las operaciones de **joins en SQL** o a concatenar hojas de cálculo en Excel.

Las dos funciones principales son:

- **`merge()`** → une DataFrames según columnas o índices comunes (como los *joins* en SQL).  
- **`concat()`** → pega DataFrames uno encima de otro (filas) o uno al lado del otro (columnas).

### <u>`merge()`: unir DataFrames como en SQL</u>

El método `merge()` permite combinar dos DataFrames usando una clave común.

#### Sintaxis básica
```python
pd.merge(df1, df2, on="columna_clave")
```

**Tipos de joins disponibles**:
- *inner* (por defecto): se queda solo con los registros comunes en ambas tablas.
- *left*: conserva todas las filas del DataFrame izquierdo.
- *right*: conserva todas las filas del DataFrame derecho.
- *outer*: conserva todas las filas de ambos, rellenando con NaN lo que falte.

In [56]:
import pandas as pd

# DataFrame con pasajeros y edades
df1 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "nombre": ["Ana", "Luis", "Marta", "Carlos"],
    "edad": [23, 34, 29, 40]
})

# DataFrame con pasajeros y ciudades
df2 = pd.DataFrame({
    "id": [2, 3, 4, 5],
    "ciudad": ["Madrid", "Barcelona", "Valencia", "Sevilla"]
})

display(df1)
display(df2)

   id  nombre  edad
0   1     Ana    23
1   2    Luis    34
2   3   Marta    29
3   4  Carlos    40

   id     ciudad
0   2     Madrid
1   3  Barcelona
2   4   Valencia
3   5    Sevilla

In [57]:
# Inner join
pd.merge(df1, df2, on="id", how="inner")

   id  nombre  edad     ciudad
0   2    Luis    34     Madrid
1   3   Marta    29  Barcelona
2   4  Carlos    40   Valencia

In [58]:
# Left join
pd.merge(df1, df2, on="id", how="left")

   id  nombre  edad     ciudad
0   1     Ana    23        NaN
1   2    Luis    34     Madrid
2   3   Marta    29  Barcelona
3   4  Carlos    40   Valencia

In [59]:
# Outer join
pd.merge(df1, df2, on="id", how="outer")

   id  nombre  edad     ciudad
0   1     Ana  23.0        NaN
1   2    Luis  34.0     Madrid
2   3   Marta  29.0  Barcelona
3   4  Carlos  40.0   Valencia
4   5     NaN   NaN    Sevilla

### <u>`concat()`: concatenar DataFrames</u>

La función `concat()` se utiliza para **apilar DataFrames**:

- Por filas (uno debajo del otro).  
- Por columnas (uno al lado del otro).  

#### Sintaxis básica
```python
pd.concat([df1, df2], axis=0)  # por filas
pd.concat([df1, df2], axis=1)  # por columnas
```

In [60]:
df_a = pd.DataFrame({"A": [1, 2], "B": [3, 4]})
df_b = pd.DataFrame({"A": [5, 6], "B": [7, 8]})

display(df_a)
display(df_b)

   A  B
0  1  3
1  2  4

   A  B
0  5  7
1  6  8

In [61]:
# Concatenación por filas
pd.concat([df_a, df_b], axis=0)

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

In [62]:
# Concatenación por columnas
df_c = pd.DataFrame({"C": ["x", "y"]})
pd.concat([df_a, df_c], axis=1)

   A  B  C
0  1  3  x
1  2  4  y

### 📝 **Ejercicios**

1. Toma el dataset Titanic reducido (`titanic_demo.csv`) y divídelo en dos:
   - `df1`: columnas `sex`, `age`, `pclass`.  
   - `df2`: columnas `fare`, `embarked`, `survived`.  
   Une ambos DataFrames con `concat()` por columnas (`axis=1`).  
---
2. Crea dos pequeños DataFrames con los mismos nombres de columnas y concaténalos por filas.  
   Observa qué ocurre con los índices y prueba a reiniciarlos con `.reset_index(drop=True)`.
---
3. (Extra) Crea dos DataFrames que no compartan todas las columnas y concaténalos.  
   ¿Qué valor aparece en las celdas que no tienen correspondencia?

## 9. Optimización y Buenas Prácticas en Pandas

Cuando trabajamos con datasets pequeños (ej. Titanic) casi no importa la eficiencia.  
Pero en proyectos reales de IA podemos tener **millones de filas** y **decenas de columnas**, lo que exige escribir código en Pandas que sea:

- **Más eficiente en memoria.**  
- **Más rápido en ejecución.**  
- **Escalable a datos grandes.**

En esta sección veremos algunas técnicas clave.

### <u>Reducción de memoria</u>

Cada columna en Pandas tiene un tipo de datos (`dtype`).  
Si usamos un tipo más grande de lo necesario, gastamos memoria innecesaria.

#### Estrategias:
- Convertir columnas con pocos valores únicos a **`category`**.  
- Usar enteros más pequeños (`int8`, `int16` en lugar de `int64`).  
- Usar decimales más pequeños (`float32` en lugar de `float64`).

In [63]:
import pandas as pd

df = pd.read_csv(os.path.join(os.getcwd(), "titanic_demo", "titanic_demo.csv"))

print("Uso de memoria original:")
print(df.memory_usage(deep=True))

print("-"*150)

# Optimización
df_opt = df.copy()
df_opt["pclass"] = df_opt["pclass"].astype("int8")
df_opt["sibsp"] = df_opt["sibsp"].astype("int8")
df_opt["parch"] = df_opt["parch"].astype("int8")
df_opt["fare"] = df_opt["fare"].astype("float32")
df_opt["sex"] = df_opt["sex"].astype("category")
df_opt["embarked"] = df_opt["embarked"].astype("category")

print("\nUso de memoria optimizado:")
print(df_opt.memory_usage(deep=True))

Uso de memoria original:
Index         132
pclass       1600
survived     1600
name        16887
sex         12358
age          1600
sibsp        1600
parch        1600
ticket      12789
fare         1600
cabin        7784
embarked    11574
dtype: int64
------------------------------------------------------------------------------------------------------------------------------------------------------

Uso de memoria optimizado:
Index         132
pclass        200
survived     1600
name        16887
sex           432
age          1600
sibsp         200
parch         200
ticket      12789
fare          800
cabin        7784
embarked      482
dtype: int64

### <u>Lectura parcial de datos</u>

No siempre es necesario cargar todo el dataset en memoria.

#### Opciones:
- **`nrows`** → lee solo un número limitado de filas.  
- **`chunksize`** → divide la lectura en bloques más pequeños (*streaming*).

In [64]:
# Leer solo las primeras 5 filas
df_small = pd.read_csv(os.path.join(os.getcwd(), "titanic_demo", "titanic_demo.csv"), nrows=5)
print(df_small)

print("-"*150)

# Leer en chunks de 5 filas
for chunk in pd.read_csv(os.path.join(os.getcwd(), "titanic_demo", "titanic_demo.csv"), chunksize=5):
    print("Chunk leído:")
    print(chunk)

   pclass  survived                      name   sex   age  sibsp  parch  \
0       3         0      Rintamaki, Mr. Matti  male  35.0      0      0
1       3         1          Nakid, Mr. Sahid  male  20.0      1      1
2       3         0     Lyntakoff, Mr. Stanko  male   NaN      0      0
3       3         0          Ford, Mr. Arthur  male   NaN      0      0
4       3         0  Shaughnessy, Mr. Patrick  male   NaN      0      0

              ticket     fare  cabin embarked
0  STON/O 2. 3101273   7.1250    NaN        S
1               2653  15.7417    NaN        C
2             349235   7.8958    NaN        S
3           A/5 1478   8.0500    NaN        S
4             370374   7.7500    NaN        Q
------------------------------------------------------------------------------------------------------------------------------------------------------
Chunk leído:
   pclass  survived                      name   sex   age  sibsp  parch  \
0       3         0      Rintamaki, Mr. Matti  male  35.0      0      0
1       3         1          Nakid, Mr. Sahid  male  20.0      1      1
2       3         0     Lyntakoff, Mr. Stanko  male   NaN      0      0
3       3         0          Ford, Mr. Arthur  male   NaN      0      0
4       3         0  Shaughnessy, Mr. Patrick  male   NaN      0      0

              ticket     fare  cabin embarked
0  STON/O 2. 3101273   7.1250    NaN        S
1               2653  15.7417    NaN        C
2             349235   7.8958    NaN        S
3           A/5 1478   8.0500    NaN        S
4             370374   7.7500    NaN        Q
Chunk leído:
   pclass  survived                                            name     sex  \
5       1         1   Romaine, Mr. Charles Hallace ('Mr C Rolmane')    male
6       3         0                 Peltomaki, Mr. Nikolai Johannes    male
7       2         1                           Wilhelms, Mr. Charles    male
8       3         0                                Kelly, Mr. James    male
9       1         1  Chambers, Mrs. Norman Campbell (Bertha Griggs)  female

    age  sibsp  parch             ticket     fare cabin embarked
5  45.0      0      0             111428  26.5500   NaN        S
6  25.0      0      0  STON/O 2. 3101291   7.9250   NaN        S
7  31.0      0      0             244270  13.0000   NaN        S
8  34.5      0      0             330911   7.8292   NaN        Q
9  33.0      1      0             113806  53.1000    E8        S
Chunk leído:
    pclass  survived                         name     sex   age  sibsp  parch  \
10       3         0     Sage, Mr. Douglas Bullen    male   NaN      8      2
11       3         0          Samaan, Mr. Youssef    male   NaN      2      0
12       3         1  Nicola-Yarred, Miss. Jamila  female  14.0      1      0
13       3         0           Ivanoff, Mr. Kanio    male   NaN      0      0
14       3         0           Markun, Mr. Johann    male  33.0      0      0

      ticket     fare  cabin embarked
10  CA. 2343  69.5500    NaN        S
11      2662  21.6792    NaN        C
12      2651  11.2417    NaN        C
13    349201   7.8958    NaN        S
14    349257   7.8958    NaN        S
Chunk leído:
    pclass  survived                                   name     sex   age  \
15       3         1              O'Driscoll, Miss. Bridget  female   NaN
16       3         0                         Saad, Mr. Amin    male   NaN
17       3         1        Nilsson, Miss. Helmina Josefina  female  26.0
18       1         1  White, Mrs. John Stuart (Ella Holmes)  female  55.0
19       3         0                Dean, Mr. Bertram Frank    male  26.0

    sibsp  parch     ticket      fare cabin embarked
15      0      0      14311    7.7500   NaN        Q
16      0      0       2671    7.2292   NaN        C
17      0      0     347470    7.8542   NaN        S
18      0      0   PC 17760  135.6333   C32        C
19      1      2  C.A. 2315   20.5750   NaN        S
Chunk leído:
    pclass  survived                               name     sex   age  sibsp  \
20       3         0        Strandberg, Miss. Ida Sofia  female  22.0      0
21       1         0           Carlsson, Mr. Frans Olof    male  33.0      0
22       3         0        Hansen, Mr. Henry Damsgaard    male  21.0      0
23       1         1   Silverthorne, Mr. Spencer Victor    male  35.0      0
24       3         1  Leeni, Mr. Fahim ('Philip Zenni')    male  22.0      0

    parch    ticket     fare        cabin embarked
20      0      7553   9.8375          NaN        S
21      0       695   5.0000  B51 B53 B55        S
22      0    350029   7.8542          NaN        S
23      0  PC 17475  26.2875          E24        S
24      0      2620   7.2250          NaN        C
Chunk leído:
    pclass  survived                           name     sex   age  sibsp  \
25       3         0        Boulos, Miss. Nourelain  female   9.0      1
26       2         0         Harbeck, Mr. William H    male  44.0      0
27       2         1  Christy, Mrs. (Alice Frances)  female  45.0      0
28       3         1      Mulvihill, Miss. Bertha E  female  24.0      0
29       1         1           Lurette, Miss. Elise  female  58.0      0

    parch    ticket      fare cabin embarked
25      1      2678   15.2458   NaN        C
26      0    248746   13.0000   NaN        S
27      2    237789   30.0000   NaN        S
28      0    382653    7.7500   NaN        Q
29      0  PC 17569  146.5208   B80        C
Chunk leído:
    pclass  survived                                               name  \
30       2         1             Portaluppi, Mr. Emilio Ilario Giuseppe
31       2         1                          Hamalainen, Master. Viljo
32       3         1                                McCoy, Miss. Alicia
33       1         1  Chaffee, Mrs. Herbert Fuller (Carrie Constance...
34       2         0                          Deacon, Mr. Percy William

       sex      age  sibsp  parch        ticket     fare cabin embarked
30    male  30.0000      0      0    C.A. 34644  12.7375   NaN        C
31    male   0.6667      1      1        250649  14.5000   NaN        S
32  female      NaN      2      0        367226  23.2500   NaN        Q
33  female  47.0000      1      0   W.E.P. 5734  61.1750   E31        S
34    male  17.0000      0      0  S.O.C. 14879  73.5000   NaN        S
Chunk leído:
    pclass  survived                                             name     sex  \
35       3         0                      Vanden Steen, Mr. Leo Peter    male
36       1         1  Minahan, Mrs. William Edward (Lillian E Thorpe)  female
37       2         0                          Fox, Mr. Stanley Hubert    male
38       1         1                      Compton, Miss. Sara Rebecca  female
39       1         0                                Lewy, Mr. Ervin G    male

     age  sibsp  parch    ticket     fare cabin embarked
35  28.0      0      0    345783   9.5000   NaN        S
36  37.0      1      0     19928  90.0000   C78        Q
37  36.0      0      0    229236  13.0000   NaN        S
38  39.0      1      1  PC 17756  83.1583   E49        C
39   NaN      0      0  PC 17612  27.7208   NaN        C
Chunk leído:
    pclass  survived                        name     sex   age  sibsp  parch  \
40       2         1         Pinsky, Mrs. (Rosa)  female  32.0      0      0
41       3         1  Dorking, Mr. Edward Arthur    male  19.0      0      0
42       2         1    Bystrom, Mrs. (Karolina)  female  42.0      0      0
43       3         0           Kink, Mr. Vincenz    male  26.0      2      0
44       3         0         Osen, Mr. Olaf Elon    male  16.0      0      0

        ticket     fare  cabin embarked
40      234604  13.0000    NaN        S
41  A/5. 10482   8.0500    NaN        S
42      236852  13.0000    NaN        S
43      315151   8.6625    NaN        S
44        7534   9.2167    NaN        S
Chunk leído:
    pclass  survived                                 name     sex   age  \
45       3         0                   Willey, Mr. Edward    male   NaN
46       3         0                  Wenzel, Mr. Linhart    male  32.5
47       3         1           Badman, Miss. Emily Louisa  female  18.0
48       2         1  Troutt, Miss. Edwina Celia 'Winnie'  female  27.0
49       3         1             Nysten, Miss. Anna Sofia  female  22.0

    sibsp  parch         ticket   fare cabin embarked
45      0      0  S.O./P.P. 751   7.55   NaN        S
46      0      0         345775   9.50   NaN        S
47      0      0      A/4 31416   8.05   NaN        S
48      0      0          34218  10.50  E101        S
49      0      0         347081   7.75   NaN        S
Chunk leído:
    pclass  survived                                               name  \
50       1         1                    Burns, Miss. Elizabeth Margaret
51       3         0                  Williams, Mr. Howard Hugh 'Harry'
52       1         1                     Peuchen, Major. Arthur Godfrey
53       1         1  Compton, Mrs. Alexander Taylor (Mary Eliza Ing...
54       3         0                        Alhomaki, Mr. Ilmari Rudolf

       sex   age  sibsp  parch            ticket      fare cabin embarked
50  female  41.0      0      0             16966  134.5000   E40        C
51    male   NaN      0      0          A/5 2466    8.0500   NaN        S
52    male  52.0      0      0            113786   30.5000  C104        S
53  female  64.0      0      2          PC 17756   83.1583   E45        C
54    male  20.0      0      0  SOTON/O2 3101287    7.9250   NaN        S
Chunk leído:
    pclass  survived                                               name  \
55       2         0                         Rogers, Mr. Reginald Harry
56       1         0                                  Fortune, Mr. Mark
57       1         1                 Cardeza, Mr. Thomas Drake Martinez
58       3         0                                  Karaic, Mr. Milan
59       3         1  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...

       sex   age  sibsp  parch            ticket      fare        cabin  \
55    male  19.0      0      0             28004   10.5000          NaN
56    male  64.0      1      4             19950  263.0000  C23 C25 C27
57    male  36.0      0      1          PC 17755  512.3292  B51 B53 B55
58    male  30.0      0      0            349246    7.8958          NaN
59  female  24.0      1      0  STON/O2. 3101279   15.8500          NaN

   embarked
55        S
56        S
57        C
58        S
59        S
Chunk leído:
    pclass  survived                         name     sex   age  sibsp  parch  \
60       2         0  Hocking, Mr. Richard George    male  23.0      2      1
61       3         1  Albimona, Mr. Nassef Cassem    male  26.0      0      0
62       1         1     Young, Miss. Marie Grice  female  36.0      0      0
63       2         1    Mellors, Mr. William John    male  19.0      0      0
64       1         1     Wick, Miss. Mary Natalie  female  31.0      0      2

       ticket      fare cabin embarked
60      29104   11.5000   NaN        S
61       2699   18.7875   NaN        C
62   PC 17760  135.6333   C32        C
63  SW/PP 751   10.5000   NaN        S
64      36928  164.8667    C7        S
Chunk leído:
    pclass  survived                                             name     sex  \
65       1         1                            Bidois, Miss. Rosalie  female
66       1         1  Bucknell, Mrs. William Robert (Emma Eliza Ward)  female
67       2         0                      Mitchell, Mr. Henry Michael    male
68       3         0                                Dakic, Mr. Branko    male
69       3         0                           Eklund, Mr. Hans Linus    male

     age  sibsp  parch      ticket      fare cabin embarked
65  42.0      0      0    PC 17757  227.5250   NaN        C
66  60.0      0      0       11813   76.2917   D15        C
67  70.0      0      0  C.A. 24580   10.5000   NaN        S
68  19.0      0      0      349228   10.1708   NaN        S
69  16.0      0      0      347074    7.7750   NaN        S
Chunk leído:
    pclass  survived                            name   sex   age  sibsp  \
70       1         0    Dulles, Mr. William Crothers  male  39.0      0
71       2         0        Bailey, Mr. Percy Andrew  male  18.0      0
72       3         0               Cor, Mr. Liudevit  male  19.0      0
73       3         1        Daly, Mr. Eugene Patrick  male  29.0      0
74       2         1  Richards, Master. William Rowe  male   3.0      1

    parch    ticket     fare cabin embarked
70      0  PC 17580  29.7000   A18        C
71      0     29108  11.5000   NaN        S
72      0    349231   7.8958   NaN        S
73      0    382651   7.7500   NaN        Q
74      1     29106  18.7500   NaN        S
Chunk leído:
    pclass  survived                                               name  \
75       3         0                             Celotti, Mr. Francesco
76       3         0                               Demetri, Mr. Marinko
77       2         0  Corey, Mrs. Percy C (Mary Phyllis Elizabeth Mi...
78       2         0                                 Weisz, Mr. Leopold
79       2         1  Laroche, Mrs. Joseph (Juliette Marie Louise La...

       sex   age  sibsp  parch         ticket     fare  cabin embarked
75    male  24.0      0      0         343275   8.0500    NaN        S
76    male   NaN      0      0         349238   7.8958    NaN        S
77  female   NaN      0      0   F.C.C. 13534  21.0000    NaN        S
78    male  27.0      1      0         228414  26.0000    NaN        S
79  female  22.0      1      2  SC/Paris 2123  41.5792    NaN        C
Chunk leído:
    pclass  survived                        name     sex   age  sibsp  parch  \
80       3         0   Carlsson, Mr. Carl Robert    male  24.0      0      0
81       3         0  Panula, Master. Juha Niilo    male   7.0      4      1
82       3         0           Lester, Mr. James    male  39.0      0      0
83       3         1             Chip, Mr. Chang    male  32.0      0      0
84       3         1          Moor, Mrs. (Beila)  female  27.0      0      1

       ticket     fare cabin embarked
80     350409   7.8542   NaN        S
81    3101295  39.6875   NaN        S
82  A/4 48871  24.1500   NaN        S
83       1601  56.4958   NaN        S
84     392096  12.4750  E121        S
Chunk leído:

    pclass  survived                                               name  \
85       2         0                   Frost, Mr. Anthony Wood 'Archie'
86       3         0                                 Davies, Mr. Joseph
87       2         1                                 Herman, Miss. Kate
88       1         1     Rothschild, Mrs. Martin (Elizabeth L. Barrett)
89       1         1  Spedden, Mrs. Frederic Oakley (Margaretta Corn...

       sex   age  sibsp  parch     ticket    fare cabin embarked
85    male   NaN      0      0     239854    0.00   NaN        S
86    male  17.0      2      0  A/4 48873    8.05   NaN        S
87  female  24.0      1      2     220845   65.00   NaN        S
88  female  54.0      1      0   PC 17603   59.40   NaN        C
89  female  40.0      1      1      16966  134.50   E34        C
Chunk leído:
    pclass  survived                               name     sex   age  sibsp  \
90       1         1            Bonnell, Miss. Caroline  female  30.0      0
91       2         0  Brown, Mr. Thomas William Solomon    male  60.0      1
92       3         0       Dahlberg, Miss. Gerda Ulrika  female  22.0      0
93       3         0                Peduzzi, Mr. Joseph    male   NaN      0
94       1         0       Crosby, Capt. Edward Gifford    male  70.0      1

    parch     ticket      fare cabin embarked
90      0      36928  164.8667    C7        S
91      1      29750   39.0000   NaN        S
92      0       7552   10.5167   NaN        S
93      0   A/5 2817    8.0500   NaN        S
94      1  WE/P 5735   71.0000   B22        S
Chunk leído:
    pclass  survived                                            name     sex  \
95       3         0                             O'Brien, Mr. Thomas    male
96       1         0                      Molson, Mr. Harry Markland    male
97       1         1  Smith, Mrs. Lucien Philip (Mary Eloise Hughes)  female
98       1         0                     Williams, Mr. Charles Duane    male
99       3         0  Klasen, Mrs. (Hulda Kristina Eugenia Lofqvist)  female

     age  sibsp  parch    ticket     fare cabin embarked
95   NaN      1      0    370365  15.5000   NaN        Q
96  55.0      0      0    113787  30.5000   C30        S
97  18.0      1      0     13695  60.0000   C31        S
98  51.0      0      1  PC 17597  61.3792   NaN        C
99  36.0      0      2    350405  12.1833   NaN        S
Chunk leído:
     pclass  survived                                         name     sex  \
100       1         0  Rosenshine, Mr. George ('Mr George Thorne')    male
101       3         1                               Lang, Mr. Fang    male
102       3         0                       Naughton, Miss. Hannah  female
103       3         0                           Henry, Miss. Delia  female
104       3         0                             Ali, Mr. William    male

      age  sibsp  parch              ticket     fare  cabin embarked
100  46.0      0      0            PC 17585  79.2000    NaN        C
101  26.0      0      0                1601  56.4958    NaN        S
102   NaN      0      0              365237   7.7500    NaN        Q
103   NaN      0      0              382649   7.7500    NaN        Q
104  25.0      0      0  SOTON/O.Q. 3101312   7.0500    NaN        S
Chunk leído:
     pclass  survived                                               name  \
105       3         0                                Lockyer, Mr. Edward
106       3         0                                Carr, Miss. Jeannie
107       3         0                               Patchett, Mr. George
108       3         1                         Shine, Miss. Ellen Natalia
109       1         1  Marvin, Mrs. Daniel Warner (Mary Graham Carmic...

        sex   age  sibsp  parch  ticket     fare cabin embarked
105    male   NaN      0      0    1222   7.8792   NaN        S
106  female  37.0      0      0  368364   7.7500   NaN        Q
107    male  19.0      0      0  358585  14.5000   NaN        S
108  female   NaN      0      0  330968   7.7792   NaN        Q
109  female  18.0      1      0  113773  53.1000   D30        S
Chunk leído:
     pclass  survived                                    name     sex   age  \
110       3         0                       Caram, Mr. Joseph    male   NaN
111       2         1                      Harris, Mr. George    male  62.0
112       3         0                    Youseff, Mr. Gerious    male  45.5
113       2         1                   Lehmann, Miss. Bertha  female  17.0
114       1         1  Taussig, Mrs. Emil (Tillie Mandelbaum)  female  39.0

     sibsp  parch       ticket     fare cabin embarked
110      1      0         2689  14.4583   NaN        C
111      0      0  S.W./PP 752  10.5000   NaN        S
112      0      0         2628   7.2250   NaN        C
113      0      0      SC 1748  12.0000   NaN        C
114      1      1       110413  79.6500   E67        S
Chunk leído:
     pclass  survived                             name     sex   age  sibsp  \
115       3         0      Warren, Mr. Charles William    male   NaN      0
116       3         0  Lovell, Mr. John Hall ('Henry')    male  20.5      0
117       1         1            Saalfeld, Mr. Adolphe    male   NaN      0
118       3         0        Makinen, Mr. Kalle Edvard    male  29.0      0
119       2         1              Webber, Miss. Susan  female  32.5      0

     parch             ticket    fare cabin embarked
115      0         C.A. 49867   7.550   NaN        S
116      0          A/5 21173   7.250   NaN        S
117      0              19988  30.500  C106        S
118      0  STON/O 2. 3101268   7.925   NaN        S
119      0              27267  13.000  E101        S
Chunk leído:
     pclass  survived                            name     sex   age  sibsp  \
120       3         0     Andersson, Mr. Johan Samuel    male  26.0      0
121       1         0          Case, Mr. Howard Brown    male  49.0      0
122       1         0             Ross, Mr. John Hugo    male  36.0      0
123       3         1  Murphy, Miss. Katherine 'Kate'  female   NaN      1
124       3         0                 Vovk, Mr. Janko    male  22.0      0

     parch  ticket     fare cabin embarked
120      0  347075   7.7750   NaN        S
121      0   19924  26.0000   NaN        S
122      0   13049  40.1250   A10        C
123      0  367230  15.5000   NaN        Q
124      0  349252   7.8958   NaN        S
Chunk leído:
     pclass  survived                                             name  \
125       3         1                                    Hee, Mr. Ling
126       2         0                              Dibden, Mr. William
127       3         0           Andersson, Miss. Ida Augusta Margareta
128       1         1  Stephenson, Mrs. Walter Bertram (Martha Eustis)
129       3         0                   Meanwell, Miss. (Marion Ogden)

        sex   age  sibsp  parch             ticket     fare cabin embarked
125    male   NaN      0      0               1601  56.4958   NaN        S
126    male  18.0      0      0       S.O.C. 14879  73.5000   NaN        S
127  female  38.0      4      2             347091   7.7750   NaN        S
128  female  52.0      1      0              36947  78.2667   D20        C
129  female   NaN      0      0  SOTON/O.Q. 392087   8.0500   NaN        S
Chunk leído:
     pclass  survived                              name     sex   age  sibsp  \
130       3         1       McGowan, Miss. Anna 'Annie'  female  15.0      0
131       2         1        Cook, Mrs. (Selena Rogers)  female  22.0      0
132       1         1             Daly, Mr. Peter Denis    male  51.0      0
133       1         1  Frolicher-Stehli, Mr. Maxmillian    male  60.0      1
134       1         0    Ostby, Mr. Engelhart Cornelius    male  65.0      0

     parch       ticket     fare cabin embarked
130      0       330923   8.0292   NaN        Q
131      0  W./C. 14266  10.5000   F33        S
132      0       113055  26.5500   E17        S
133      1        13567  79.2000   B41        C
134      1       113509  61.9792   B30        C
Chunk leído:
     pclass  survived                                        name     sex  \
135       1         0      Straus, Mrs. Isidor (Rosalie Ida Blun)  female
136       3         0  Soholt, Mr. Peter Andreas Lauritz Andersen    male
137       3         0                         Windelov, Mr. Einar    male
138       3         0            Petroff, Mr. Pastcho ('Pentcho')    male
139       3         1  Kink-Heilmann, Mrs. Anton (Luise Heilmann)  female

      age  sibsp  parch            ticket      fare    cabin embarked
135  63.0      1      0          PC 17483  221.7792  C55 C57        S
136  19.0      0      0            348124    7.6500    F G73        S
137  21.0      0      0  SOTON/OQ 3101317    7.2500      NaN        S
138   NaN      0      0            349215    7.8958      NaN        S
139  26.0      1      1            315153   22.0250      NaN        S
Chunk leído:
     pclass  survived                                          name     sex  \
140       3         0                          Matinoff, Mr. Nicola    male
141       1         0                             Gee, Mr. Arthur H    male
142       3         1  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female
143       1         1                  Ostby, Miss. Helene Ragnhild  female
144       2         0                         Campbell, Mr. William    male

      age  sibsp  parch   ticket     fare cabin embarked
140   NaN      0      0   349255   7.8958   NaN        C
141  47.0      0      0   111320  38.5000   E63        S
142  22.0      1      1  3101298  12.2875   NaN        S
143  22.0      0      1   113509  61.9792   B36        C
144   NaN      0      0   239853   0.0000   NaN        S
Chunk leído:
     pclass  survived                                   name     sex   age  \
145       2         0  Corbett, Mrs. Walter H (Irene Colvin)  female  30.0
146       3         0             Rommetvedt, Mr. Knud Paust    male   NaN
147       3         0                 Sutehall, Mr. Henry Jr    male  25.0
148       3         0           Hegarty, Miss. Hanora 'Nora'  female  18.0
149       3         1                 Moss, Mr. Albert Johan    male   NaN

     sibsp  parch           ticket    fare  cabin embarked
145      0      0           237249  13.000    NaN        S
146      0      0           312993   7.775    NaN        S
147      0      0  SOTON/OQ 392076   7.050    NaN        S
148      0      0           365226   6.750    NaN        Q
149      0      0           312991   7.775    NaN        S
Chunk leído:
     pclass  survived                                               name  \
150       3         1  Dyker, Mrs. Adolf Fredrik (Anna Elisabeth Judi...
151       3         1                        Howard, Miss. May Elizabeth
152       1         1          Bjornstrom-Steffansson, Mr. Mauritz Hakan
153       3         1                            Hedman, Mr. Oskar Arvid
154       2         0                         Chapman, Mr. Charles Henry

        sex   age  sibsp  parch       ticket    fare cabin embarked
150  female  22.0      1      0       347072  13.900   NaN        S
151  female   NaN      0      0  A. 2. 39186   8.050   NaN        S
152    male  28.0      0      0       110564  26.550   C52        S
153    male  27.0      0      0       347089   6.975   NaN        S
154    male  52.0      0      0       248731  13.500   NaN        S
Chunk leído:
     pclass  survived                         name     sex   age  sibsp  \
155       1         1             Blank, Mr. Henry    male  40.0      0
156       2         1         Watt, Miss. Bertha J  female  12.0      0
157       3         0  Van Impe, Mr. Jean Baptiste    male  36.0      1
158       3         0            Lane, Mr. Patrick    male   NaN      0
159       3         0         Angheloff, Mr. Minko    male  26.0      0

     parch      ticket     fare cabin embarked
155      0      112277  31.0000   A31        C
156      0  C.A. 33595  15.7500   NaN        S
157      1      345773  24.1500   NaN        S
158      0        7935   7.7500   NaN        Q
159      0      349202   7.8958   NaN        S
Chunk leído:
     pclass  survived                                   name     sex   age  \
160       1         0  Chisholm, Mr. Roderick Robert Crispin    male   NaN
161       3         1        Stanley, Miss. Amy Zillah Elsie  female  23.0
162       3         1           Tornquist, Mr. William Henry    male  25.0
163       3         0                       Miles, Mr. Frank    male   NaN
164       2         1                  Laroche, Miss. Louise  female   1.0

     sibsp  parch         ticket     fare  cabin embarked
160      0      0         112051   0.0000    NaN        S
161      0      0       CA. 2314   7.5500    NaN        S
162      0      0           LINE   0.0000    NaN        S
163      0      0         359306   8.0500    NaN        S
164      1      2  SC/Paris 2123  41.5792    NaN        C
Chunk leído:
     pclass  survived                            name     sex   age  sibsp  \
165       3         0  Nieminen, Miss. Manta Josefina  female  29.0      0
166       3         0           Pekoniemi, Mr. Edvard    male  21.0      0
167       3         1  McDermott, Miss. Brigdet Delia  female   NaN      0
168       3         0  Nirva, Mr. Iisakki Antino Aijo    male  41.0      0
169       2         1           Sinkkonen, Miss. Anna  female  30.0      0

     parch             ticket     fare  cabin embarked
165      0            3101297   7.9250    NaN        S
166      0  STON/O 2. 3101294   7.9250    NaN        S
167      0             330932   7.7875    NaN        Q
168      0   SOTON/O2 3101272   7.1250    NaN        S
169      0             250648  13.0000    NaN        S
Chunk leído:
     pclass  survived                                               name  \
170       1         1   Candee, Mrs. Edward (Helen Churchill Hungerford)
171       1         1                         Fortune, Miss. Mabel Helen
172       1         1  Hays, Mrs. Charles Melville (Clara Jennings Gr...
173       3         1                                   Osman, Mrs. Mara
174       2         1                  Harper, Miss. Annie Jessie 'Nina'

        sex   age  sibsp  parch    ticket      fare        cabin embarked
170  female  53.0      0      0  PC 17606   27.4458          NaN        C
171  female  23.0      3      2     19950  263.0000  C23 C25 C27        S
172  female  52.0      1      1     12749   93.5000          B69        S
173  female  31.0      0      0    349244    8.6833          NaN        S
174  female   6.0      0      1    248727   33.0000          NaN        S
Chunk leído:
     pclass  survived                                           name     sex  \
175       1         0                       Warren, Mr. Frank Manley    male
176       1         1  Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female
177       3         0        Andersson, Master. Sigvard Harald Elias    male
178       3         1                        Masselmani, Mrs. Fatima  female
179       3         0                      Wittevrongel, Mr. Camille    male

      age  sibsp  parch  ticket     fare cabin embarked
175  64.0      1      0  110813  75.2500   D37        C
176  56.0      0      1   11767  83.1583   C50        C
177   4.0      4      2  347082  31.2750   NaN        S
178   NaN      0      0    2649   7.2250   NaN        C
179  36.0      0      0  345771   9.5000   NaN        S
Chunk leído:
     pclass  survived                                               name  \
180       2         1  Wells, Mrs. Arthur Henry ('Addie' Dart Trevaskis)
181       1         1                               Marechal, Mr. Pierre
182       3         0                             Gheorgheff, Mr. Stanio
183       1         1                       Oliva y Ocana, Dona. Fermina
184       3         0                                Turcin, Mr. Stjepan

        sex   age  sibsp  parch    ticket      fare cabin embarked
180  female  29.0      0      2     29103   23.0000   NaN        S
181    male   NaN      0      0     11774   29.7000   C47        C
182    male   NaN      0      0    349254    7.8958   NaN        C
183  female  39.0      0      0  PC 17758  108.9000  C105        C
184    male  36.0      0      0    349247    7.8958   NaN        S

Chunk leído:
     pclass  survived                                          name     sex  \
185       1         1          Flegenheim, Mrs. Alfred (Antoinette)  female
186       3         1  Andersson, Mr. August Edvard ('Wennerstrom')    male
187       3         1                      Moubarek, Master. Gerios    male
188       3         1         Nakid, Mrs. Said (Waika 'Mary' Mowad)  female
189       3         0      Rosblom, Mrs. Viktor (Helena Wilhelmina)  female

      age  sibsp  parch    ticket     fare  cabin embarked
185   NaN      0      0  PC 17598  31.6833    NaN        S
186  27.0      0      0    350043   7.7958    NaN        S
187   NaN      1      1      2661  15.2458    NaN        C
188  19.0      1      1      2653  15.7417    NaN        C
189  41.0      0      2    370129  20.2125    NaN        S
Chunk leído:
     pclass  survived                          name   sex   age  sibsp  parch  \
190       3         0              Thomas, Mr. John  male   NaN      0      0
191       3         0         Skoog, Master. Harald  male   4.0      3      2
192       3         0      Olsen, Mr. Henry Margido  male  28.0      0      0
193       2         1  Williams, Mr. Charles Eugene  male   NaN      0      0
194       3         0         Betros, Master. Seman  male   NaN      0      0

     ticket     fare  cabin embarked
190    2681   6.4375    NaN        C
191  347088  27.9000    NaN        S
192  C 4001  22.5250    NaN        S
193  244373  13.0000    NaN        S
194    2622   7.2292    NaN        C
Chunk leído:
     pclass  survived                                              name  \
195       3         0                             Sirayanian, Mr. Orsen
196       3         0                          Allen, Mr. William Henry
197       3         0                      Sage, Miss. Constance Gladys
198       2         1  Becker, Mrs. Allen Oliver (Nellie E Baumgardner)
199       1         1                               Icard, Miss. Amelie

        sex   age  sibsp  parch    ticket     fare cabin embarked
195    male  22.0      0      0      2669   7.2292   NaN        C
196    male  35.0      0      0    373450   8.0500   NaN        S
197  female   NaN      8      2  CA. 2343  69.5500   NaN        S
198  female  36.0      0      3    230136  39.0000    F4        S
199  female  38.0      0      0    113572  80.0000   B28      NaN

### <u>Vectorización vs. `apply`</u>

Pandas está diseñado para operar sobre **columnas enteras** (vectorización).  
Esto es mucho más rápido que aplicar funciones fila a fila.

#### Ejemplo:

In [65]:
# Vectorizado (rápido)
df["fare_doble"] = df["fare"] * 2

# Con apply (más lento)
df["fare_doble_apply"] = df["fare"].apply(lambda x: x * 2)

df[["fare", "fare_doble", "fare_doble_apply"]].head()

      fare  fare_doble  fare_doble_apply
0   7.1250     14.2500           14.2500
1  15.7417     31.4834           31.4834
2   7.8958     15.7916           15.7916
3   8.0500     16.1000           16.1000
4   7.7500     15.5000           15.5000

<u>Regla general</u>: **usa operaciones vectorizadas siempre que sea posible**.  
`apply` solo debe usarse cuando la lógica no pueda expresarse de forma vectorizada.

### <u>Medición de tiempos con `%timeit`</u>

En Jupyter Notebook podemos usar **`%timeit`** para medir tiempos de ejecución de una celda o línea de código.
    
Esto nos ayuda a comparar enfoques y elegir el más eficiente.

Normalmente el vectorizado es entre **10 y 100 veces más rápido** que usar `apply`.

In [66]:
# Ejemplo: comparar vectorizado vs apply
import numpy as np

# Generamos una columna grande para ver diferencias
df_big = pd.DataFrame({"valores": np.random.rand(1_000_000)})

# Vectorizado
%timeit df_big["valores"] * 2

# Con apply
%timeit df_big["valores"].apply(lambda x: x * 2)

6.65 ms ± 272 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
690 ms ± 70.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

## 10. Preparación de Datos para IA

Antes de entrenar un modelo de Machine Learning, debemos transformar los datos en un formato **numérico, limpio y normalizado**.  
Los algoritmos no entienden directamente cadenas de texto ni categorías; por eso necesitamos aplicar **preprocesamiento**.

En esta sección veremos:
- Selección de columnas (features relevantes).  
- Codificación de variables categóricas (one-hot encoding, label encoding).  
- Normalización y escalado numérico.  
- Obtención de un DataFrame listo para modelado.

### <u>Selección de columnas y features relevantes</u>

Un **feature** es una variable que usaremos como entrada en un modelo.  
No todas las columnas de un DataFrame son útiles para entrenar:

- Algunas son identificadores (`id`, `nombre`) → no aportan información.  
- Otras son redundantes o derivadas.  
- Debemos decidir qué columnas usar como **X** (features) y cuál como **y** (target).  

Ejemplo con Titanic reducido:

In [67]:
df = pd.read_csv(os.path.join(os.getcwd(), "titanic_demo", "titanic_demo.csv"))

# Target = columna a predecir
y = df["survived"]

# Features seleccionadas
X = df[["pclass", "sex", "age", "fare", "embarked"]]
X.head()

   pclass   sex   age     fare embarked
0       3  male  35.0   7.1250        S
1       3  male  20.0  15.7417        C
2       3  male   NaN   7.8958        S
3       3  male   NaN   8.0500        S
4       3  male   NaN   7.7500        Q

### <u>One-hot encoding con `pd.get_dummies()`</u>

Los algoritmos no entienden variables categóricas (`sex`, `embarked`).  
Una opción es usar **One-Hot Encoding**, que crea una columna binaria (0/1) por cada categoría.

En Pandas podemos hacerlo fácilmente con `pd.get_dummies()`.

In [68]:
X_encoded = pd.get_dummies(X, columns=["sex", "embarked"])
X_encoded

,pclass,age,fare,sex_female,sex_male,embarked_C,embarked_Q,embarked_S
0,3,35.0,7.1250,0,1,0,0,1
1,3,20.0,15.7417,0,1,1,0,0
2,3,NaN,7.8958,0,1,0,0,1
3,3,NaN,8.0500,0,1,0,0,1
4,3,NaN,7.7500,0,1,0,1,0
...,...,...,...,...,...,...,...,...
195,3,22.0,7.2292,0,1,1,0,0
196,3,35.0,8.0500,0,1,0,0,1
197,3,NaN,69.5500,1,0,0,0,1
198,2,36.0,39.0000,1,0,0,0,1
199,1,38.0,80.0000,1,0,0,0,0

### <u>LabelEncoder y MinMaxScaler</u>

Para tareas de preprocesamiento más avanzadas solemos usar **scikit-learn**.  

- **LabelEncoder** → convierte categorías en enteros (`male=0`, `female=1`).  
- **MinMaxScaler** → normaliza valores numéricos a un rango, normalmente `[0,1]`.  

Esto es útil para algoritmos sensibles a la escala de las variables (ej. redes neuronales).

In [69]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

# Copiamos el DataFrame
X_ml = X.copy()

# LabelEncoder en 'sex' y 'embarked'
le_sex = LabelEncoder()
X_ml["sex"] = le_sex.fit_transform(X_ml["sex"])

le_emb = LabelEncoder()
X_ml["embarked"] = le_emb.fit_transform(X_ml["embarked"].astype(str))

# MinMaxScaler en columnas numéricas
scaler = MinMaxScaler()
X_ml[["age", "fare"]] = scaler.fit_transform(X_ml[["age", "fare"]])

X_ml.head()

   pclass  sex       age      fare  embarked
0       3    1  0.495192  0.013907         2
1       3    1  0.278846  0.030726         0
2       3    1       NaN  0.015412         2
3       3    1       NaN  0.015713         2
4       3    1       NaN  0.015127         1

### <u>DataFrame listo para modelado</u>

Después de estas transformaciones, tenemos un DataFrame **totalmente numérico**, sin valores categóricos ni escalas inconsistentes.

Este `X_ml` se puede usar directamente en cualquier modelo de Machine Learning:

- Árboles de decisión, Random Forest, Gradient Boosting.  
- Redes neuronales en TensorFlow/PyTorch.  
- Regresiones y clasificadores en Scikit-learn.

## 11. Reto integrador - Dataset de Ventas Online

En este ejercicio vas a trabajar con un **dataset simulado de ventas de una tienda online**.  
Contiene 500 registros de pedidos con información de clientes, productos y precios.

---

#### **Descripción del dataset**

El archivo `ventas.csv` contiene las siguientes columnas:

- **order_id** → Identificador único del pedido.  
- **customer_id** → Identificador del cliente.  
- **product** → Producto comprado.  
- **category** → Categoría del producto (`Electrónica`, `Ropa`, `Hogar`, `Juguetes`).  
- **quantity** → Cantidad de unidades compradas.  
- **price** → Precio unitario del producto.  
- **discount** → Descuento aplicado al pedido (0–0.5).  
- **order_date** → Fecha del pedido.  
- **region** → Región de envío (`Norte`, `Sur`, `Este`, `Oeste`).  
- **delivered** → Indica si el pedido fue entregado (`Yes`/`No`).

El archivo `clientes.csv` contiene las siguientes columnas:

- **customer_id** → Identificador del cliente. 
- **age** → Edad del cliente.  
- **gender** → Género del cliente.  

---

#### **Tareas**

#### <u>Lectura y exploración inicial</u>
1. Lee el dataset desde `ventas.csv`.  
2. Muestra las **primeras 10 filas** y consulta las dimensiones.  
3. Revisar tipos de datos y estadísticas.  

---

#### <u>Limpieza y manejo de valores faltantes</u>
1. Comprueba cuántos valores nulos hay en cada columna.  
2. Rellena los valores nulos en `discount` con **0**.  
3. Rellena los valores nulos en `region` con la **moda** de la columna.  

---

#### <u>Conversión de tipos y optimización</u>
1. Convierte `region` y `category` en **categorías**.  
2. Convierte `delivered` en booleano.  
3. Optimiza `quantity` como `int8`.  
4. Mide el **uso de memoria** antes y después de los cambios.  

---

#### <u>Filtrado e indexación</u>
1. Obtén todos los pedidos con `quantity > 3` y `discount > 0.2`.  
2. Selecciona las columnas `product`, `quantity` y `discount` de las **primeras 5 filas**.  
3. Selecciona con `.loc[]` todos los pedidos de la categoría `"Electrónica"` en la región `"Norte"`.  

---

#### <u>Agregaciones y estadísticas</u>
1. Calcula el **precio medio** por categoría de producto.  
2. Calcula la **cantidad total vendida** por región.  
3. Obtén la tasa de entrega (`delivered`) por categoría de producto.  

---

#### <u>Combinación de DataFrames</u>
1. Haz un `merge()` entre `ventas` y `clientes` para unir la información.  
2. Usa `concat()` para simular añadir **50 pedidos nuevos** al DataFrame original.  

---

#### <u>Vectorización vs. apply</u>
1. Calcula una nueva columna `total` = `(quantity * price) * (1 - discount)` de dos formas:  
   - Vectorizada.  
   - Con `.apply()`.  
2. Usa `%timeit` para comparar ambas soluciones.  

---

#### <u>Preparación para IA</u>
1. Selecciona como features (`X`) las columnas: `quantity`, `price`, `discount`, `region`, `category`, `gender`.  
   El target (`y`) será la columna `delivered`.  
2. Aplica **One-Hot Encoding** a `region`, `category` y `gender`.  
3. Escala las columnas numéricas (`quantity`, `price`, `discount`) con **MinMaxScaler**.  
4. Comprueba que el DataFrame final contiene únicamente **valores numéricos** listos para un modelo de Machine Learning.  

---

#### **Preguntas de reflexión**

1. ¿Qué columnas eran realmente relevantes para el análisis?  
2. ¿Cuánto se redujo el uso de memoria al optimizar los `dtypes`?  
3. ¿Por qué es mejor usar **vectorización** en vez de `.apply()` cuando se puede?  
4. ¿Qué riesgos hay al aplicar One-Hot Encoding en datasets con muchas categorías distintas?

## 12. Recursos recomendados

- Documentación oficial de Python: https://docs.python.org/3/
- PEP 8 (estilo de código): https://peps.python.org/pep-0008/
- Documentación oficial Pandas: https://pandas.pydata.org/